# Python for Big Data Processing (Tutorial )

Python coding styles:
 1. Procedural Programming
 2. Object-oriented Programming
 3. Functional Programming





### Procedural Programming

- Group instructions into procedures
- A program is set of step-by-step instructions and easy
- This coding style favors iteration, sequencing and selection.

In [22]:
balance = 0
#print(balance)

balance = balance + 100
#print(balance)

balance = balance - 10
#print(balance)

In [2]:
#Data structure
L1=[12, "Ravi", "B.Tech FY", 78.50] #list
T1=(12, "Ravi", "B.Tech FY", 78.50)#tuple
D1={"Rollno":12, "class":"B.Tech FY", "precentage":78.50}#dictionary
#print (L1[2])
#print (T1[2])
#print (D1['class'])

In [28]:
D1['mail'] = "abc.com"
#print(D1)
D1.values()

dict_values([12, 'B.Tech FY', 78.5, 'abc.com'])

In [12]:
list1 = [1,"Python",['a','e']]
#print(list1[2])

In [26]:
balance = 0

def deposit(balance, amount):
    balance = balance + amount
    return balance

def withdraw(balance, amount):
    balance = balance - amount
    return balance

#print(balance)

balance = deposit(balance,100)
#print(balance)

balance = withdraw(balance,10)
#print(balance)

In [27]:
balance = 100

def deposit(balance, amount):
  balance = balance + amount
  return balance

def withdraw(balance, amount):
  balance = balance - amount
  return balance

#print(balance)

balance = withdraw(balance,10)
#print(balance)

balance = deposit(balance,100)
#print(balance)

## Exercise
Write a Python program to multiply all the values in a dictionary without using in-built function.

In [30]:
dict1 = {'a': 100, 'b':200, 'c':300}

In [31]:
def do_add(dict1):

    sum = 1

    for x in dict1.values():

        sum *= x

    return sum

print(do_add(dict1))

6000000


### Object-oriented Programming
- Everything is an object (an abstract data type):
  - state: attributes or instance variables
  - behaviour: methods (what you do with the state)

- A program is a set of interacting objects

In [33]:
class Account:

    def __init__(self): # constructor
        self.balance = 10 # instance variable
  
    def check_balance(self): # method
        return self.balance

    def deposit(self, amount):
        self.balance = self.balance + amount
        return self.balance

    def withdraw(self, amount):
        self.balance = self.balance - amount
        return self.balance
  
account1 = Account() # instance (`self`) is passed automatically
#print(account1.check_balance())
#print(account1.deposit(100))
#print(account1.withdraw(10))

In [16]:
account2 = Account() # instance (`self`) is passed automatically
#print(account2.check_balance())
#print(account2.withdraw(10))
#print(account2.deposit(100))

### Functional Programming

- Functions/expressions instead of instructions
- A program consists entirely of evaluation of pure functions
  - stateless
    - state information is not stored
    - the output depends only on the input
  - arguments are immutable: incoming data is not mutated
- Easy to debugging


### Python Recursion




In [34]:
%%time
# Python program to display the Fibonacci nth term

def recur_fibo(n):
   if n <= 1:
       return n
   else:
       return(recur_fibo(n-1) + recur_fibo(n-2))

#nterms = 10

# check if the number of terms is valid
'''if nterms <= 0:
   print("Plese enter a positive integer")
else:
   print("Fibonacci sequence:")
   for i in range(nterms):'''
print(recur_fibo(40))


102334155
CPU times: user 40.6 s, sys: 0 ns, total: 40.6 s
Wall time: 40.6 s


In [7]:
%%time
Dict={0:0, 1:1}
def fibo(n):
    if n not in Dict:
        val=fibo(n-1)+fibo(n-2)
        Dict[n]=val
    return Dict[n]
n=100
print("Fibonacci(", n,")= ", fibo(n))

Fibonacci( 100 )=  354224848179261915075
CPU times: user 783 µs, sys: 96 µs, total: 879 µs
Wall time: 908 µs


### In-built functions for functional programming in python

In [9]:
list2 = [100,1000,10000]

In [10]:
sum(list2)

11100

#### Lambda
- A lambda function can take any number of arguments, but can only have one expression.

- syntax: `lambda parameter_list: expression`

In [51]:
square = lambda x: x*x

print(square(5))

25


> square(5)

> lambda 5

> 5 * 5

In [16]:
#two arguments
sum1 = lambda a,b: a+b
print(sum1(1,2))


3


In [23]:
multi =lambda a, b, c : a * b * c
print(multi(5, 2, 6))


60


In [22]:
message = lambda: print("Hello World!")
 
message()

Hello World!


In [35]:
reverse = (lambda s: s[::-1])("I am a string")
reverse

'gnirts a ma I'




- `filter`
- `map`
- `reduce`

#### `filter`
- `filter (function, iterable) --> iterator`
- apply `function` to each item in the iterable
- if the result is true, append the result to the iterator

In [21]:
numbers = [1,2,3,4,5]
oddnums = filter(lambda x: x%2 ==1, numbers)
print(list(oddnums))#output always from the list

[1, 3, 5]


In [40]:
def odd_num(x):
    return x % 2 == 1
list(filter(odd_num, numbers))

[1, 3, 5]

#### `map`
- `map (function, iterable [,iterable 2, ..., iterable n]) --> iterator`
- apply `function` to each item in each iterable, append the result tuples to the iterator

In [46]:
numbers = [1,2,3,4,5]
results = map(lambda x: x+1, numbers)
print(list(results))

[2, 3, 4, 5, 6]


In [70]:
num1 = [1,2,3,4,5]
num2 = [5,4,3,2,1]
results = map(lambda x,y: x*y, num1, num2)
print(list(results))

[5, 8, 9, 8, 5]


In [71]:
num1 = [1,2,3]
num2 = [4,5,6]
num3 = [7,8,9]
results = map(lambda x,y,z: x*y+z, num1, num2, num3)
print(list(results))

[11, 18, 27]


In [28]:
squares1 = []
for x in range(10):
    squares1.append(x**2)

print(squares1)
squares1.remove(9)
#squares1.clear()
#print(squares1)
#print(squares1.count(16))
#print(len(squares1))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


Exercise: Print the above list using 'map' and 'lamda'

In [29]:
squares2 = list(map(lambda x: x**2, range(10)))
squares2

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

#### `reduce`
- `reduce (function, iterable, initializer = None) --> value`
- go through iterable, apply function, and produce final reduced value

In [48]:
from functools import reduce #python3

numbers = [1,2,3,4,5,6,7]
sum = reduce(lambda acc,x: acc + x, numbers)
print(sum)

28


In [49]:
numbers = [1,2,3,4,5,6,7]
product = reduce(lambda acc,x: acc * x, numbers)
print(product)


5040


In [50]:
def f(x, y):
    return x + y
reduce(f, [1, 2, 3, 4, 5])

15

In [16]:
#Another Procedural Programming

starting_number = 10

# get the square of the number
square = starting_number ** 2

# increment the number by 1
increment = square + 1

# cube of the number
cube = increment ** 3

# decrease the cube by 1
decrement = cube - 1

# get the final result
print(decrement)

1030300


### Exercise: Transfer from Procedural language to functional programming using above inbuilt function

In [18]:
# define a function `call` where you provide the function and the arguments
def call(x, f):
    return f(x)

# define a function that returns the square
square = lambda x : x*x

# define a function that returns the increment
increment = lambda x : x+1

# define a function that returns the cube
cube = lambda x : x*x*x

# define a function that returns the decrement
decrement = lambda x : x-1
# put all the functions in a list in the order that you want to execute them
funcs = [square, increment, cube, decrement]

# bring it all together. Below is the non functional part. 
# in functional programming you separate the functional and the non functional parts.
from functools import reduce # reduce is in the functools library
print(reduce(call, funcs, 10)) 


1030300


In [53]:
'''A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
 
# take a 3x4 matrix   
B = [[5, 8, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]
     
result = [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]
 
# iterating by row of A
for i in range(len(A)):
 
    # iterating by column by B
    for j in range(len(B[0])):
 
        # iterating by rows of B
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]
 
for r in result:
    print(r)
len(B[0])'''

'A = [[12, 7, 3],\n    [4, 5, 6],\n    [7, 8, 9]]\n \n# take a 3x4 matrix   \nB = [[5, 8, 1, 2],\n    [6, 7, 3, 0],\n    [4, 5, 9, 1]]\n     \nresult = [[0, 0, 0, 0],\n        [0, 0, 0, 0],\n        [0, 0, 0, 0]]\n \n# iterating by row of A\nfor i in range(len(A)):\n \n    # iterating by column by B\n    for j in range(len(B[0])):\n \n        # iterating by rows of B\n        for k in range(len(B)):\n            result[i][j] += A[i][k] * B[k][j]\n \nfor r in result:\n    print(r)\nlen(B[0])'

In [54]:
'''A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
 
# take a 3x4 matrix
B = [[5, 8, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]
 
# result will be 3x4
result = [[sum(a * b for a, b in zip(A_row, B_col))
                        for B_col in zip(*B)]
                                for A_row in A]
 
for r in result:
    print(r)'''

'A = [[12, 7, 3],\n    [4, 5, 6],\n    [7, 8, 9]]\n \n# take a 3x4 matrix\nB = [[5, 8, 1, 2],\n    [6, 7, 3, 0],\n    [4, 5, 9, 1]]\n \n# result will be 3x4\nresult = [[sum(a * b for a, b in zip(A_row, B_col))\n                        for B_col in zip(*B)]\n                                for A_row in A]\n \nfor r in result:\n    print(r)'

In [9]:
import numpy as np
# two dimensional arrays
m1 = np.array([[12, 7, 3],
               [4, 5, 6],
               [7, 8, 9]])
m2 = np.array([[5, 8, 1, 2],
              [6, 7, 3, 0],
              [4, 5, 9, 1]])
m3 = np.dot(m1,m2) 
m31 = m1@m2
print(m3)
print(m31)

[[114 160  60  27]
 [ 74  97  73  14]
 [119 157 112  23]]
[[114 160  60  27]
 [ 74  97  73  14]
 [119 157 112  23]]


**References:**
1. [Programming paradigms supported by different languages](https://en.wikipedia.org/wiki/Comparison_of_multi-paradigm_programming_languages#Language_overview)

2. [Comparison of programming paradigms](https://www.cs.ucf.edu/~leavens/ComS541Fall97/hw-pages/paradigms/major.html)

3. [Numpy](https://numpy.org/)